import { JEE, UPSC, SSC } from "../assets/img";

export const Exams = [
  {
    id:"jeemains",
    examName: "JEE Mains 2023",
    src: JEE,
    altText: "Jee image",
    examOrganisation: "National testing agency",
    totalStudents: "More than 20 lakhs",
    examFees: "₹ 1200",
    categories: ["Engineering", "IIT", "PCM"],
  },
  {
    id: "upsc",
    examName: "Civil services 2023",
    src: UPSC,
    altText: "Upsc image",
    examOrganisation: "Union Public Service Commission",
    totalStudents: "More than 15 lakhs",
    examFees: "₹ 1500",
    categories: ["Engineering", "PCM"],
  },
  {
    id: "ssc",
    examName: "SSC CGL 2023",
    src: SSC,
    altText: "Ssc image",
    examOrganisation: "Staff selection commission",
    totalStudents: "More than 10 lakhs",
    examFees: "₹ 1000",
    categories: ["Engineering", "PCM"],
  },
  {
    id: "ssc",
    examName: "SSC CGL 2023",
    src: SSC,
    altText: "Ssc image",
    examOrganisation: "Staff selection commission",
    totalStudents: "More than 10 lakhs",
    examFees: "₹ 1200",
    categories: ["Engineering", "PCM"],
  },
];

export const Exams2 = [
  {
    id: "vitjee",
    examName: "VITJEE 2023",
    src: JEE,
    altText: "Jee image",
    examOrganisation: "Vellore institute of technology",
    totalStudents: "More than 20 lakhs",
    examFees: "₹ 1500",
    categories: ["Engineering", "PCM"],
  },
  {
    id: "srmjee",
    examName: "SRMJEE2023",
    src: UPSC,
    altText: "Upsc image",
    examOrganisation: "SRMIST",
    totalStudents: "More than 15 lakhs",
    examFees: "₹ 1000",
    categories: ["Engineering", "PCM"],
  },
  {
    id: "tseamcet",
    examName: "TSEAMCET 2023",
    src: SSC,
    altText: "Ssc image",
    examOrganisation: "TSCHE",
    totalStudents: "More than 10 lakhs",
    examFees: "₹ 1000",
    categories: ["Engineering", "PCM"],
  },
  {
    id:  "ssc",
    examName: "SSC CGL 2023",
    src: SSC,
    altText: "Ssc image",
    examOrganisation: "Staff selection commission",
    totalStudents: "More than 10 lakhs",
    examFees: "₹ 1200",
    categories: ["Engineering", "PCM"],
  },
];